gsettings set org.gnome.shell.extensions.system-monitor cpu-style 'digit'
gsettings set org.gnome.shell.extensions.system-monitor cpu-show-text false
gsettings set org.gnome.shell.extensions.system-monitor disk-show-menu false
gsettings set org.gnome.shell.extensions.system-monitor fan-sensor-file '/sys/class/hwmon/hwmon4/fan1_input'
gsettings set org.gnome.shell.extensions.system-monitor fan-show-menu true
gsettings set org.gnome.shell.extensions.system-monitor fan-style 'digit'
gsettings set org.gnome.shell.extensions.system-monitor icon-display false
gsettings set org.gnome.shell.extensions.system-monitor memory-refresh-time 1500
gsettings set org.gnome.shell.extensions.system-monitor memory-style 'digit'
gsettings set org.gnome.shell.extensions.system-monitor memory-show-text false
gsettings set org.gnome.shell.extensions.system-monitor net-style 'digit'
gsettings set org.gnome.shell.extensions.system-monitor net-show-text false
gsettings set org.gnome.shell.extensions.system-monitor swap-style 'digit'
gsettings set org.gnome.shell.extensions.system-monitor thermal-display true
gsettings set org.gnome.shell.extensions.system-monitor thermal-sensor-file '/sys/class/hwmon/hwmon5/temp1_input'
gsettings set org.gnome.shell.extensions.system-monitor thermal-refresh-time 1500
gsettings set org.gnome.shell.extensions.system-monitor thermal-style 'digit'
gsettings set org.gnome.shell.extensions.system-monitor thermal-show-text false
gsettings set org.gnome.shell.extensions.system-monitor thermal-threshold 59
